[workspace]
members = ["api", "."]

[package]
name = "keiko"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
dojo-world = { git = "https://github.com/dojoengine/dojo.git", tag = "v0.3.10", features = ["manifest"] }
katana-core = { git = "https://github.com/dojoengine/dojo.git", tag = "v0.3.10" }
blockifier = { git = "https://github.com/starkware-libs/blockifier" }
axum = "0.6.20"
jsonrpsee-http-client = "0.20.0"
serde = "1.0.183"
serde_json = "1.0.104"
tokio = { version = "1.31.0", features = ["full"] }
url = "2.5.0"

[patch."https://github.com/starkware-libs/blockifier"]
blockifier = { git = "https://github.com/dojoengine/blockifier", rev = "3357e69" }

[patch.crates-io]
cairo-felt = { git = "https://github.com/dojoengine/cairo-rs.git", rev = "262b7eb4b11ab165a2a936a5f914e78aa732d4a2" }
cairo-vm = { git = "https://github.com/dojoengine/cairo-rs.git", rev = "262b7eb4b11ab165a2a936a5f914e78aa732d4a2" }

[dependencies]
dojo-world.workspace = true
blockifier.workspace = true
axum.workspace = true
katana-core.workspace = true
jsonrpsee-http-client.workspace = true
tokio.workspace = true
url.workspace = true
clap = { version = "4.4.8", features = ["derive", "env"] }
keiko-api = { path = './api' }
log = "0.4.20"
run_script = "0.10.1"
tower-http = { version = "0.4.3", features = ["add-extension", "fs", "cors"] }
